source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'Faro_Example' do
  pod "Faro", path: "../"
  pod 'Stella', git: 'https://github.com/icapps/ios-stella.git', branch: 'develop'
  pod 'BuddyBuildSDK'

  target 'Faro_Tests' do
	  pod 'Quick',   '~> 1.2'
	  pod 'Nimble', '~> 7.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        if target.name == 'Faro'
            config.build_settings['SWIFT_VERSION'] = '4.0'
        else
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
  end
end
