source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!

target 'AirRivet_Example' do
  pod "AirRivet", :path => "../"

  target 'AirRivet_Tests' do
    inherit! :search_paths

	# Testing dependencies.
	pod 'Quick', '~> 1.0'
	pod 'Nimble', '~> 5.1'
  end
end
