source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Faro_Example' do
  pod "Faro", :path => "../"
  pod 'Stella', :git => 'https://github.com/icapps/ios-stella.git',
                :branch => 'feature/swift3.0'

  target 'Faro_Tests' do
      # The test frameworks
      pod 'Quick',  :git => 'https://github.com/Quick/Quick.git',
                    :branch => 'swift-3.0'
      pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git'
  end
end
